### ISSUE TITLE
How to predict future isoscape based on “Fit the isoscape models”?

### ISSUE THREAD

**Issue by Otoliths** [courtiol/IsoriX#137]
Hi Courtiol,
      I have prepared isotopic composition data and environmental data in the same time and space. How to predict future isoscape based on “Fit the isoscape models” and future environmental layers？

Thanks!
Liuyong

**Comment by courtiol** [comment]
Hi, please join the google group for questions about how to do something: https://groups.google.com/g/isorix/
When you will write something there, please also give some more details about your data because for now I don't exactly understand what you are trying to do: what environmental predictors are you using?
